name: docker-android-sdk 

on:
  workflow_dispatch:

jobs:
  build_multiarch:
    runs-on: ubuntu-latest
    name: ${{ matrix.distro }} image build on ${{ matrix.arch }}
    
    strategy:
      matrix:
        include:
          - arch: arm64
            distro: ubuntu
          - arch: arm64
            distro: alpine
          - arch: amd64
            distro: alpine
          - arch: amd64
            distro: alpine
        
    steps:
      - name: Check-out 
        uses: actions/checkout@master
        with:
          repository: mindrunner/docker-android-sdk
    
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image (docker-android-sdk:alpine-standalone)
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --tag ghcr.io/asklios/docker-android-sdk:${{ matrix.distro }}-standalone-${{ matrix.arch }} \
            -f ./${{ matrix.distro }}/standalone/Dockerfile .
          docker push ghcr.io/asklios/docker-android-sdk:${{ matrix.distro }}-standalone-${{ matrix.arch }}
