name: freescout-mariadb

on:
  workflow_dispatch:
  
jobs:
  build_arm64:
    runs-on: self-hosted
    steps:
      
      - name: Check out docker-mariadb
        uses: actions/checkout@master
        with:
          repository:  tiredofit/docker-mariadb 
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: build & push image (docker-freescout-mariadb:latest)
        run: |
          docker build \
            --tag ghcr.io/asklios/docker-freescout-mariadb:latest .
          docker push ghcr.io/asklios/docker-freescout-mariadb:latest
