name: docker-nginx-certbot

on:
  workflow_dispatch:

jobs:
  build_multiarch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check-out 
        uses: actions/checkout@master
    
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image (docker-android-sdk:${{ matrix.distro }}-standalone)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/asklios/docker-nginx-certbot:latest \
            -f ./nginx-certbot-alpine .
          docker push ghcr.io/asklios/docker-nginx-certbot:latest
