name: docker-nginx-certbot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  multiarch_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check-out 
        uses: actions/checkout@master
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image (docker-nginx-certbot:latest)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./nginx-certbot-alpine
          context: .
          tags: |
            ghcr.io/asklios/docker-nginx-certbot:latest
