name: matrix-dimension

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build_multiarch:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check-out local
        uses: actions/checkout@master
        with:
          path: local
    
      - name: checkout matrix-dimension
        uses: actions/checkout@master
        with:
          repository: turt2live/matrix-dimension
          path: dimension
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: build & push image (matrix-dimension:latest)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: local/matrix-dimension
          context: ./dimension/
          tags: |
            ghcr.io/asklios/matrix-dimension_test:latest
