name: docker-android-sdk 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out 
        uses: actions/checkout@master
        with:
          repository: mindrunner/docker-android-sdk
    
    - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image (docker-android-sdk:alpine-lazydl)
        run: |
          docker buildx build \
            --tag asklios/docker-android-sdk:alpine-lazydl \
            --platform linux/amd64,linux/arm64 ./alpine/lazydl/
          docker push ghcr.io/asklios/docker-android-sdk
      
      - name: build & push image (docker-android-sdk:alpine-standalone)
        run: |
          docker buildx build \
            --tag asklios/docker-android-sdk:alpine-standalone \
            --platform linux/amd64,linux/arm64 ./alpine/standalone/
          docker push ghcr.io/asklios/docker-android-sdk
          
      - name: build & push image (docker-android-sdk:ubuntu-lazydl)
        run: |
          docker buildx build \
            --tag asklios/docker-android-sdk:ubuntu-lazydl \
            --platform linux/amd64,linux/arm64 ./ubuntu/lazydl/
          docker push ghcr.io/asklios/docker-android-sdk
      
      - name: build & push image (docker-android-sdk:ubuntu-standalone)
        run: |
          docker buildx build \
            --tag asklios/docker-android-sdk:ubuntu-standalone \
            --platform linux/amd64,linux/arm64 ./ubuntu/standalone/
          docker push ghcr.io/asklios/docker-android-sdk
