name: docker-android-sdk 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out 
        uses: actions/checkout@master
        with:
          repository: mindrunner/docker-android-sdk
          arch: aarch64
    
      - name: setup docker
        uses: docker-practice/actions-setup-docker@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image (docker-android-sdk:alpine-standalone)
        run: |
          docker build \
            --tag asklios/docker-android-sdk:alpine-standalone \
            -f ./alpine/standalone/Dockerfile .
          docker push ghcr.io/asklios/docker-android-sdk
      
      - name: build & push image (docker-android-sdk:ubuntu-standalone)
        run: |
          docker build \
            --tag asklios/docker-android-sdk:ubuntu-standalone \
            -f ./ubuntu/standalone/Dockerfile .
          docker push ghcr.io/asklios/docker-android-sdk
