name: docker-android-sdk 

on:
  workflow_dispatch:

jobs:
  build_amd64:
    runs-on: ubuntu-latest
    name: ${{ matrix.distro }} image build on amd64
    
    strategy:
      matrix:
        include:
          - distro: ubuntu
          - distro: alpine
        
    steps:
      - name: Check-out 
        uses: actions/checkout@master
        with:
          repository: mindrunner/docker-android-sdk
    
      - name: setup docker
        uses: docker-practice/actions-setup-docker@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image (docker-android-sdk:${{ matrix.distro }}-standalone)
        run: |
          docker build \
            --tag ghcr.io/asklios/docker-android-sdk:${{ matrix.distro }}-standalone-amd64 \
            -f ./${{ matrix.distro }}/standalone/Dockerfile .
          docker push ghcr.io/asklios/docker-android-sdk:${{ matrix.distro }}-standalone-amd64

  build_arm64:
    runs-on: self-hosted
    name: ${{ matrix.distro }} image build on arm64
    
    strategy:
      matrix:
        include:
          - distro: ubuntu
          - distro: alpine
        
    steps:
      - name: Check-out 
        uses: actions/checkout@master
        with:
          repository: mindrunner/docker-android-sdk
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image (docker-android-sdk:${{ matrix.distro }}-standalone)
        run: |
          docker build \
            --tag ghcr.io/asklios/docker-android-sdk:${{ matrix.distro }}-standalone-arm64 \
            -f ./${{ matrix.distro }}/standalone/Dockerfile .
          docker push ghcr.io/asklios/docker-android-sdk:${{ matrix.distro }}-standalone-arm64
