name: keycloak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out Keycloak-Containers
        uses: actions/checkout@master
        with:
          repository: keycloak/keycloak-containers
      
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image
        run: |
          docker buildx build \
            --tag asklios/keycloak:latest \
            --platform linux/amd64,linux/arm64 ./server/
          docker push ghcr.io/asklios/keycloak
