name: keycloak

on:
  workflow_dispatch:

jobs:
  build_amd64:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out Keycloak-Containers
        uses: actions/checkout@master
        with:
          repository: keycloak/keycloak-containers
      
      - name: setup docker
        uses: docker-practice/actions-setup-docker@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image
        run: |
          docker build \
            --tag ghcr.io/asklios/keycloak:amd64 \
            -f ./server/Dockerfile ./server/
          docker push ghcr.io/asklios/keycloak:amd64
          
  build_arm64:
    runs-on: self-hosted
    steps:
      
      - name: Check out Keycloak-Containers
        uses: actions/checkout@master
        with:
          repository: keycloak/keycloak-containers
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: build & push image
        run: |
          docker build \
            --tag ghcr.io/asklios/keycloak:arm64 \
            -f ./server/Dockerfile ./server/
          docker push ghcr.io/asklios/keycloak:arm64
